package icapa;

import icapa.models.Ontology;

public class Playground {

    public static void main(String[] args) throws Exception {
        String table = "HelloWorld";
        String idColumn = "\"" + table + "Id\"";
        String augment = idColumn + " INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, CONSTRAINT pk PRIMARY KEY (" + idColumn + ")";
        String query = Util.getCreateTableQuery(table, augment);
        System.out.println(query);
    }
}
